'use strict';
const RM=typeof matchMedia==='function'?matchMedia('(prefers-reduced-motion: reduce)'):{matches:false};const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const CHAPTERS=['Small Workshop','Town Packing Plant','Automated Factory','Giant Logistics Hub','Global Enterprise'];
const SUBLEVELS=['Opening','Equipment Upgrades','Scaling Up','Efficiency','Mastery'];
const SAVE_KEY='shift-walk-factory-v2';
const MAP_SCALE=2,SPEED_K=MAP_SCALE/1.4,MAP_W=19*MAP_SCALE,MAP_D=16*MAP_SCALE;let terrain=false;
const S={stage:0,money:0,total:0,sold:0,stageSold:0,gear:0,quality:0,workers:0,stock:24,raw:0,parts:0,packIn:0,products:0,scrap:0,heat:0,packHeat:0,procProgress:0,secondProgress:0,packProgress:0,time:0,orderCount:0,orderIndex:0,orderTimer:0,orderUrgent:false,chain:0,chainTimer:0,power:0,powerCooldown:0,refillCooldown:0,exports:0,cleaned:0,orders:0,paused:false,sound:false};
const player={id:0,x:4.9*MAP_SCALE,z:5.0*MAP_SCALE,cargo:null,count:0,premium:false,actionTime:0,zone:null,bought:null,paintTime:0,slow:0,moving:false,dir:1};
const actors=[player],spills=[],particles=[],cashFloats=[];
const chapter=()=>Math.floor(S.stage/5),level=()=>S.stage%5;
const unitPrice=()=>Math.round(14*Math.pow(1.6,chapter())*(1+.07*level())*(1+.12*S.quality));
const capacity=()=>Math.min(8,2+Math.floor(S.gear/2)+Math.floor(chapter()/2));
const staffLimit=()=>Math.min(6,2+chapter());
const bufferCap=()=>12+chapter()*4;
const stockCap=()=>30+chapter()*8;
const machineTime=()=>Math.max(.9,1.9/(1+.055*S.gear))/(S.power>0?1.35:1);
const packTime=()=>Math.max(.75,1.3/(1+.045*S.gear))/(S.power>0?1.25:1);
const expansionCost=()=>Math.round(14*Math.pow(1.6,chapter())*(18+level()*7+chapter()*8));
const expansionGoal=()=>10+level()*4+chapter()*5;
const upgradeCost=id=>{const b=14*Math.pow(1.6,chapter());return Math.round(id==='gear'?b*(5+S.gear*3.5):id==='quality'?b*(7+S.quality*4):b*(10+S.workers*9)*(1+S.workers*.18))};
const maxUpgrade=()=>Math.min(10,3+chapter()*2);
const orderGoal=()=>S.orderUrgent?6+chapter()*2:8+chapter()*3;
const orderBonus=()=>unitPrice()*(S.orderUrgent?6+chapter()*2:4+chapter());
const fmt=n=>'$'+Math.floor(n).toLocaleString('en-US');
const stations=[
 {id:'source',name:'Material Yard',x:2.6,z:2.8,color:'#dca656',icon:'🪵',type:'source'},
 {id:'proc',name:'Processor',x:7.2,z:2.8,color:'#69bdc9',icon:'⚙️',type:'proc'},
 {id:'pack',name:'Packing Bench',x:11.8,z:2.8,color:'#7dabdc',icon:'📦',type:'pack'},
 {id:'supply',name:'Restock',x:2.6,z:6.4,color:'#83c28c',icon:'🚚',type:'utility'},
 {id:'scrap',name:'Scrap Bin',x:2.6,z:10.0,color:'#b5aa8e',icon:'♻',type:'scrap'},
 {id:'recycle',name:'Recycler',x:7.2,z:10.0,color:'#65b799',icon:'♻',type:'recycle'},
 {id:'cool',name:'Cooling',x:7.2,z:6.4,color:'#57c5e8',icon:'❄',type:'utility'},
 {id:'power',name:'Power Boost',x:11.8,z:6.4,color:'#eed373',icon:'ϟ',type:'utility'},
 {id:'delivery',name:'Delivery',x:11.8,z:13.4,color:'#d9b16e',icon:'¥',type:'delivery'},
 {id:'gear',name:'Gear Bench',x:2.6,z:13.4,color:'#b5de76',icon:'🔧',type:'upgrade'},
 {id:'workers',name:'Hiring Desk',x:7.2,z:13.4,color:'#91c6ed',icon:'👷',type:'upgrade'},
 {id:'quality',name:'Quality Lab',x:11.8,z:10.0,color:'#c2a5ee',icon:'◆',type:'upgrade'},
 {id:'expand',name:'Expansion Gate',x:16.4,z:10.0,color:'#bafa66',icon:'↗',type:'upgrade'},
 {id:'proc2',name:'2nd Processor',x:16.4,z:2.8,color:'#69bdc9',icon:'⚙️',type:'proc',unlock:1},
 {id:'paint',name:'Paint Booth',x:16.4,z:6.4,color:'#e4a7c4',icon:'🎨',type:'paint',unlock:2},
 {id:'export',name:'Export Truck',x:16.4,z:13.4,color:'#c6aa71',icon:'🌐',type:'export',unlock:4}
];
for(const st of stations){st.x*=MAP_SCALE;st.z*=MAP_SCALE}
let lastGrowth='',camReset=true,width=900,height=600,tile=24,camX=0,camY=0,drag=null,keys=new Set(),toastTimer,celebrateTimer,audioCtx,saveTimer=0,uiTimer=0,last=performance.now(),accumulator=0,rafId,helpWasPaused=false;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function sound(type){if(!S.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const notes=type==='expand'?[523,659,784,1047]:type==='cash'?[783,1046]:[440,587];notes.forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=f;const t=audioCtx.currentTime+i*.07;g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.15);o.start(t);o.stop(t+.16)})}catch{}}
function burst(x,z,n=20,colors=['#ffda6b','#bafa66'],large=false){if(RM.matches)return;for(let i=0;i<n&&particles.length<400;i++)particles.push({x,z,h:.6,vx:(Math.random()-.5)*(large?7:3),vz:(Math.random()-.5)*(large?7:3),vh:3+Math.random()*6,life:large?2.8:1.5,age:0,color:colors[i%colors.length],size:large?.12:.075})}
function earn(amount,x,z,label){amount=Math.max(0,Math.round(amount));S.money+=amount;S.total+=amount;cashFloats.push({x,z,text:label||'+'+fmt(amount),age:0});burst(x,z,18);sound('cash')}
function createWorker(id){return {id,x:(7.5+Math.random()*.6)*MAP_SCALE,z:14.8*MAP_SCALE,cargo:null,count:0,premium:false,actionTime:0,zone:null,bought:null,paintTime:0,slow:0,moving:false,dir:1,target:null,wait:0,path:[],planAt:0}}
function save(){try{const state={...S,paused:false,sound:false,procProgress:0,secondProgress:0,packProgress:0};localStorage.setItem(SAVE_KEY,JSON.stringify({version:2,layout:4,state,player:{x:player.x,z:player.z,cargo:player.cargo,count:player.count,premium:player.premium},actors:actors.slice(1).map(a=>({x:a.x,z:a.z,cargo:a.cargo,count:a.count,premium:a.premium}))}));$('save-status').textContent='Saved on this device · No purchases, no ads'}catch{$('save-status').textContent='Saving unavailable · progress resets when you close this page'}}
function load(){try{const data=JSON.parse(localStorage.getItem(SAVE_KEY));if(data?.version!==2)return;const t=data.state;if(!Number.isInteger(t.stage)||t.stage<0||t.stage>24)return;for(const k of Object.keys(S))if(typeof S[k]==='number'&&Number.isFinite(t[k]))S[k]=Math.max(0,t[k]);S.stage=Math.min(24,Math.floor(S.stage));S.gear=Math.min(10,Math.floor(S.gear));S.quality=Math.min(10,Math.floor(S.quality));S.workers=Math.min(staffLimit(),Math.floor(S.workers));S.stock=Math.min(stockCap(),S.stock);S.raw=Math.min(bufferCap(),S.raw);S.parts=Math.min(bufferCap(),S.parts);S.packIn=Math.min(bufferCap(),S.packIn);S.products=Math.min(bufferCap(),S.products);S.orderUrgent=!!t.orderUrgent;for(const [a,p] of [[player,data.player]]){if(p&&data.layout===4&&Number.isFinite(p.x)&&Number.isFinite(p.z)){a.x=Math.max(.7,Math.min(MAP_W-.7,p.x));a.z=Math.max(1,Math.min(MAP_D-.4,p.z));a.cargo=['raw','part','product','scrap'].includes(p.cargo)?p.cargo:null;a.count=a.cargo?Math.min(capacity(),Math.max(1,Math.floor(p.count)||1)):0;a.premium=!!p.premium}}
 for(let i=1;i<=S.workers;i++){const a=createWorker(i),p=data.actors?.[i-1];if(p){a.cargo=['raw','part','product'].includes(p.cargo)?p.cargo:null;a.count=a.cargo?Math.min(capacity(),Math.max(1,Math.floor(p.count)||1)):0;a.premium=!!p.premium}actors.push(a)}}catch{}}
function isUnlocked(st){return !st.unlock||chapter()>=st.unlock}
function ensureWalkable(a){if(!blocked(a.x,a.z))return;const x=a.x,z=a.z;for(let radius=.3;radius<4;radius+=.3)for(const [dx,dz] of [[0,1],[0,-1],[1,0],[-1,0]]){if(!blocked(x+dx*radius,z+dz*radius)){a.x=x+dx*radius;a.z=z+dz*radius;a.target=null;a.path=[];return}}a.x=.8;a.z=MAP_D-.5;}
function stationAvailable(st,a=player){if(!isUnlocked(st))return false;if(st.type==='upgrade'){if(st.id==='expand')return S.stage<24&&S.money>=expansionCost()&&S.stageSold>=expansionGoal();return S[st.id]<(st.id==='workers'?staffLimit():maxUpgrade())&&S.money>=upgradeCost(st.id)}if(st.id==='source')return (!a.cargo||a.cargo==='raw')&&a.count<capacity()&&S.stock>0;if(st.type==='proc')return a.cargo==='raw'?S.raw<bufferCap():(!a.cargo||a.cargo==='part')&&a.count<capacity()&&S.parts>0;if(st.id==='pack')return a.cargo==='part'?S.packIn<bufferCap():(!a.cargo||a.cargo==='product')&&!a.premium&&a.count<capacity()&&S.products>0;if(st.id==='delivery'||st.id==='export')return a.cargo==='product'&&a.count>0;if(st.id==='paint')return a.cargo==='product'&&!a.premium;if(st.id==='scrap')return !a.cargo&&S.scrap>0;if(st.id==='recycle')return a.cargo==='scrap';if(st.id==='cool')return S.heat+S.packHeat>8;if(st.id==='supply')return S.refillCooldown===0&&S.stock<stockCap();if(st.id==='power')return S.powerCooldown===0;return false;}
function recommendedStation(){const get=id=>stations.find(st=>st.id===id),closest=ids=>ids.map(get).filter(st=>stationAvailable(st)).sort((a,b)=>Math.hypot(a.x-player.x,a.z+1.55-player.z)-Math.hypot(b.x-player.x,b.z+1.55-player.z))[0]||null;if(player.cargo==='product'){if(!player.premium&&stationAvailable(get('paint')))return get('paint');return chapter()>=4?get('export'):get('delivery')}if(player.cargo==='scrap')return get('recycle');if(player.cargo==='raw'){if(S.heat>82&&stationAvailable(get('cool')))return get('cool');return closest(['proc','proc2'])||(stationAvailable(get('cool'))?get('cool'):stationAvailable(get('power'))?get('power'):null)}if(player.cargo==='part'){if(S.packHeat>82)return get('cool');return stationAvailable(get('pack'))?get('pack'):stationAvailable(get('cool'))?get('cool'):stationAvailable(get('power'))?get('power'):null}if(stationAvailable(get('expand')))return get('expand');if(S.workers===0&&stationAvailable(get('workers')))return get('workers');if(S.products>0)return get('pack');if(S.parts>0&&chapter()<3)return closest(['proc','proc2']);if(S.heat>82||S.packHeat>82)return get('cool');if(S.stock>0&&S.raw<bufferCap())return get('source');if(!S.stock&&stationAvailable(get('supply')))return get('supply');if(stationAvailable(get('power'))&&S.raw+S.packIn>0)return get('power');if(stationAvailable(get('scrap')))return get('scrap');return null;}
function drawDestinationPin(dest){const p=project(dest.x,dest.z,1.05+Math.sin(S.time*4)*.1),x=Math.max(20,Math.min(width-20,p.x)),y=Math.max(100,Math.min(height-110,p.y)),off=x!==p.x||y!==p.y;ctx.save();ctx.translate(x,y);ctx.rotate(off?Math.atan2(p.y-y,p.x-x)-Math.PI/2:0);poly([{x:-9,y:-8},{x:9,y:-8},{x:0,y:7}],'#a7f3ff','#275a6b');ctx.restore();}
function tapDestinationAt(x,y){const hits=[];for(const st of stations){if(!isUnlocked(st))continue;const label=project(st.x,st.z,2.7),body=project(st.x,st.z,.9),pad=project(st.x,st.z+1.55,.02);ctx.font='700 12px system-ui';const labelWidth=ctx.measureText(st.name).width/2+12;if(Math.abs(x-label.x)<labelWidth&&Math.abs(y-label.y)<13)hits.push({st,score:Math.hypot(x-label.x,y-label.y)});else if(Math.abs(x-body.x)<tile*2.1&&Math.abs(y-body.y)<tile*1.9)hits.push({st,score:Math.hypot(x-body.x,y-body.y)+10});else if(Math.hypot((x-pad.x)/tile,(y-pad.y)/(tile*.5))<1)hits.push({st,score:Math.hypot(x-pad.x,y-pad.y)+5})}if(hits.length){hits.sort((a,b)=>a.score-b.score);const st=hits[0].st;return {x:st.x,z:st.z+1.55,station:st.id}}const sx=(x-width/2-camX)/tile,sy=(y-height*.15-camY)/(tile*.5);return {x:(sx+sy)/2,z:(sy-sx)/2,station:null};}
function navigatePlayer(dest){if(S.paused||!dest)return false;const x=Math.max(.7,Math.min(MAP_W-.5,dest.x)),z=Math.max(1.05,Math.min(MAP_D-.3,dest.z));if(!planPath(player,{x,z:z-1.55})){toast('Cannot move there');return false}player.autoPath=true;const last=player.path[player.path.length-1]||{x,z};player.tapDestination={x:last.x,z:last.z,station:dest.station};player.navStuck=0;return true;}

function nearStation(a){let closest=null,d=1.04;for(const st of stations){const dist=Math.hypot(a.x-st.x,a.z-(st.z+1.55));if(dist<d){d=dist;closest=st}}return closest}
function buyAt(id){if(S.paused)return false;const cap=id==='workers'?staffLimit():maxUpgrade();if(S[id==='gear'?'gear':id==='quality'?'quality':'workers']>=cap)return false;const cost=upgradeCost(id);if(S.money<cost)return false;S.money-=cost;S[id]++;if(id==='workers')actors.push(createWorker(S.workers));sound('buy');burst(player.x,player.z,32,['#bafa66','#8de2ff']);toast(id==='gear'?`Gear Lv.${S.gear}! Carry ${capacity()} / faster movement & processing`:id==='workers'?'A teammate joined! They collect, process, pack and deliver':'Quality up! Every delivery pays more');save();return true}
function expandAt(){if(S.paused||S.stage>=24||S.money<expansionCost()||S.stageSold<expansionGoal())return false;S.money-=expansionCost();S.stage++;for(const a of actors)ensureWalkable(a);S.stageSold=0;S.stock=Math.min(stockCap(),S.stock+8);S.heat=Math.max(0,S.heat-35);S.packHeat=Math.max(0,S.packHeat-35);$('celebrate-sub').textContent=level()===0?'NEW CHAPTER UNLOCKED':'LEVEL '+(level()+1)+' / 5 · EXPANDED';$('celebrate-title').textContent=level()===0?CHAPTERS[chapter()]:SUBLEVELS[level()]+' complete';$('celebrate-detail').textContent=level()===0?['','2nd Processor unlocked!','Paint Booth raises delivery value!','Conveyor now moves parts automatically!','Export Truck gives big bonuses!'][chapter()]:`Unit price ${fmt(unitPrice())} · On to the next level`;$('celebration').classList.add('show');clearTimeout(celebrateTimer);celebrateTimer=setTimeout(()=>$('celebration').classList.remove('show'),2400);burst(player.x,player.z,150,['#bafa66','#ffda6b','#71d9d0','#d5afff'],true);sound('expand');save();return true}
function deliver(a,st,exporting=false){if(a.cargo!=='product'||!a.count)return false;const count=a.count;if(!a.id){S.chain=S.chainTimer>0?Math.min(5,S.chain+1):1;S.chainTimer=22}const bonus=!a.id?1+.05*(S.chain-1):1;earn(unitPrice()*count*(a.premium?1.6:1)*bonus*(exporting?1.35:1),st.x,st.z);S.sold+=count;S.stageSold+=count;S.orderCount+=count;if(exporting)S.exports+=count;a.cargo=null;a.count=0;a.premium=false;if(S.orderCount>=orderGoal()){const reward=orderBonus();S.orders++;S.orderIndex++;S.orderCount=0;earn(reward,st.x,st.z,'Order complete +'+fmt(reward));toast('Order complete! '+fmt(reward)+' bonus');S.orderUrgent=chapter()>=1&&S.orderIndex%3===2;S.orderTimer=S.orderUrgent?90:0;}return true}
function interact(a,st,dt){if(!isUnlocked(st))return;const wait=a.id? .3:.35;if(a.moving){a.actionTime=0;return}a.actionTime+=dt;if(st.type==='upgrade'){if(a.id||a.bought===st.id)return;const allowed=st.id==='expand'?S.stage<24&&S.money>=expansionCost()&&S.stageSold>=expansionGoal():S.money>=upgradeCost(st.id)&&S[st.id]<(st.id==='workers'?staffLimit():maxUpgrade());if(!allowed){a.actionTime=0;return}if(a.actionTime>=1.3){const success=st.id==='expand'?expandAt():buyAt(st.id);if(success)a.bought=st.id;a.actionTime=0}return}
 if(st.id==='paint'){if(a.cargo!=='product'||a.premium){a.paintTime=0;return}a.paintTime+=dt;if(a.paintTime>=2.2){a.premium=true;a.paintTime=0;burst(st.x,st.z,20,['#f2aedd','#c8abff']);if(!a.id)toast('Painted! Delivery value ×1.6')}return}
 if(a.actionTime<wait)return;a.actionTime=0;
 if(st.id==='source'){if(a.cargo&&a.cargo!=='raw')return;const count=Math.min(S.stock,capacity()-a.count);if(count>0){S.stock-=count;a.cargo='raw';a.count+=count;burst(st.x,st.z,4,['#d3b779'])}}
 else if(st.type==='proc'){if(a.cargo==='raw'){const n=Math.min(a.count,bufferCap()-S.raw);S.raw+=n;a.count-=n;if(!a.id)a.dropped=st.id;if(!a.count)a.cargo=null}else if(a.dropped!==st.id&&(!a.cargo||a.cargo==='part')&&a.count<capacity()&&S.parts>0){const n=Math.min(capacity()-a.count,S.parts);a.count+=n;S.parts-=n;a.cargo='part'}}
 else if(st.id==='pack'){if(a.cargo==='part'){const n=Math.min(a.count,bufferCap()-S.packIn);S.packIn+=n;a.count-=n;if(!a.id)a.dropped=st.id;if(!a.count)a.cargo=null}else if(a.dropped!==st.id&&(!a.cargo||a.cargo==='product')&&!a.premium&&a.count<capacity()&&S.products>0){const n=Math.min(capacity()-a.count,S.products);a.count+=n;S.products-=n;a.cargo='product'}}
 else if(st.id==='delivery'||st.id==='export')deliver(a,st,st.id==='export');
 else if(st.id==='scrap'&&!a.cargo&&S.scrap>0){a.count=Math.min(capacity(),S.scrap);S.scrap-=a.count;a.cargo='scrap'}
 else if(st.id==='recycle'&&a.cargo==='scrap'){earn(unitPrice()*.4*a.count,st.x,st.z);a.count=0;a.cargo=null;if(!a.id)toast('Scrap turned into cash!')}
 else if(st.id==='cool'){const h=S.heat+S.packHeat;S.heat=Math.max(0,S.heat-22);S.packHeat=Math.max(0,S.packHeat-22);if(h>10)burst(st.x,st.z,7,['#94ecff','#fff']);}
 else if(st.id==='supply'&&!S.refillCooldown){S.stock=stockCap();S.refillCooldown=30;burst(st.x,st.z,16,['#bafa66','#e3edc2']);if(!a.id)toast('Materials arrived! Stock refilled')}
 else if(st.id==='power'&&!S.powerCooldown){S.power=18;S.powerCooldown=65;burst(st.x,st.z,26,['#ffd65c','#fff6c9']);if(!a.id)toast('18s of faster processing & packing!')}
}
function blocked(x,z){if(x<.65||x>MAP_W-.4||z<1||z>MAP_D-.2)return true;for(const st of stations){if(!isUnlocked(st))continue;if(x>st.x-1.08&&x<st.x+1.08&&z>st.z-.75&&z<st.z+.73)return true}return false}
function move(a,dx,dz,dt){let n=Math.hypot(dx,dz);if(!n){a.moving=false;return}dx/=n;dz/=n;let speed=3.25*SPEED_K*(1+.045*S.gear)*(a.id?.91:1)*(a.slow>0?.55:1)*(a.cargo?.94:1);const nx=a.x+dx*speed*dt,nz=a.z+dz*speed*dt;const oldX=a.x,oldZ=a.z;let moved=false;if(!blocked(nx,a.z)){a.x=nx;moved=true}if(!blocked(a.x,nz)){a.z=nz;moved=true}a.moving=moved;if(moved){a.facingX=dx;a.facingZ=dz;a.walkPhase=(a.walkPhase||0)+Math.hypot(a.x-oldX,a.z-oldZ)*3.4;}if(dx+dz!==0)a.dir=dx+dz>0?1:-1;}
const gridStep=.5;
function planPath(a,st){const desired={x:st.x,z:st.z+1.55},sx=Math.round(a.x/gridStep),sz=Math.round(a.z/gridStep),key=(x,z)=>(x+300)*1000+(z+300);let gx=Math.round(desired.x/gridStep),gz=Math.round(desired.z/gridStep);if(blocked(gx*gridStep,gz*gridStep)){let candidate=null;for(let dx=-3;dx<=3;dx++)for(let dz=-3;dz<=3;dz++){const x=gx+dx,z=gz+dz;if(blocked(x*gridStep,z*gridStep))continue;const dist=Math.hypot(x*gridStep-desired.x,z*gridStep-desired.z);if(!candidate||dist<candidate.dist)candidate={x,z,dist}}if(!candidate){a.path=[];return false}gx=candidate.x;gz=candidate.z;desired.x=gx*gridStep;desired.z=gz*gridStep}const start=key(sx,sz),goal=key(gx,gz),queue=[[sx,sz]],prev=new Map([[start,null]]);let found=false;for(let i=0;i<queue.length&&i<14000;i++){const [x,z]=queue[i];if(key(x,z)===goal){found=true;break}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,k=key(nx,nz);if(prev.has(k)||blocked(nx*gridStep,nz*gridStep))continue;prev.set(k,key(x,z));queue.push([nx,nz])}}if(!found){a.path=[];return false}const path=[];let k=goal;while(k!==start&&k){const x=Math.floor(k/1000)-300,z=k%1000-300;path.unshift({x:x*gridStep,z:z*gridStep});k=prev.get(k)}if(!blocked(desired.x,desired.z))path.push(desired);a.path=path;return true;}

function chooseTarget(a){if(a.cargo==='product')return chapter()>=4&&a.id%2===0?'export':'delivery';if(a.cargo==='raw')return chapter()>=1&&a.id%2===0?'proc2':'proc';if(a.cargo==='part')return 'pack';if(S.products>0)return 'pack';if(S.parts>0&&chapter()<3)return chapter()>=1&&a.id%2===0?'proc2':'proc';if(S.raw<bufferCap()&&S.stock>0)return 'source';if(S.heat>65||S.packHeat>65)return 'cool';return 'pack'}
let stockFraction=0,spillClock=0,conveyorClock=0,paintSmoke=0;
function update(dt){if(S.paused)return;S.time+=dt;stockFraction+=dt*(.8+chapter()*.16);if(stockFraction>=1){const n=Math.floor(stockFraction);stockFraction-=n;S.stock=Math.min(stockCap(),S.stock+n)}S.heat=Math.max(0,S.heat-dt*2.25);S.packHeat=Math.max(0,S.packHeat-dt*2.1);S.power=Math.max(0,S.power-dt);S.powerCooldown=Math.max(0,S.powerCooldown-dt);S.refillCooldown=Math.max(0,S.refillCooldown-dt);S.chainTimer=Math.max(0,S.chainTimer-dt);if(S.chainTimer===0)S.chain=0;
 const process=(field,second=false)=>{if(S.raw>0&&S.parts<bufferCap()&&S.heat<92){S[field]+=dt/(machineTime()*(second?1.12:1));if(S[field]>=1){S[field]-=1;S.raw--;S.parts++;S.heat=Math.min(100,S.heat+5);if((S.parts+S.sold)%7===0)S.scrap=Math.min(12,S.scrap+1)}}else S[field]=Math.min(.99,S[field])};process('procProgress');if(chapter()>=1)process('secondProgress',true);if(S.packIn>0&&S.products<bufferCap()&&S.packHeat<92){S.packProgress+=dt/packTime();if(S.packProgress>=1){S.packProgress-=1;S.packIn--;S.products++;S.packHeat=Math.min(100,S.packHeat+4)}}
 if(chapter()>=3){conveyorClock+=dt;if(conveyorClock>=.85){conveyorClock=0;if(S.parts>0&&S.packIn<bufferCap()){S.parts--;S.packIn++;}}}
 if(S.orderUrgent){S.orderTimer=Math.max(0,S.orderTimer-dt);if(S.orderTimer===0){S.orderUrgent=false;S.orderCount=0;toast('Rush order ended. Back to regular orders.')}}
 let sx=0,sy=0;if(keys.has('KeyD')||keys.has('ArrowRight'))sx++;if(keys.has('KeyA')||keys.has('ArrowLeft'))sx--;if(keys.has('KeyS')||keys.has('ArrowDown'))sy++;if(keys.has('KeyW')||keys.has('ArrowUp'))sy--;if(drag){const dx=drag.x-drag.startX,dy=drag.y-drag.startY;const len=Math.hypot(dx,dy);if(len>7){sx=dx/len;sy=dy/len}}if(sx||sy){player.autoPath=false;player.path=[];player.tapDestination=null;move(player,(sx+sy*2)/2,(sy*2-sx)/2,dt)}else if(player.autoPath&&!drag){const p=player.path[0];if(p){const dist=Math.hypot(player.x-p.x,player.z-p.z);if(dist<.12){player.path.shift();player.moving=false;}else{const oldX=player.x,oldZ=player.z;move(player,p.x-player.x,p.z-player.z,dt);player.navStuck=Math.hypot(player.x-oldX,player.z-oldZ)<.0001?(player.navStuck||0)+dt:0;if(player.navStuck>1){if(!planPath(player,{x:player.tapDestination.x,z:player.tapDestination.z-1.55})){player.autoPath=false;player.tapDestination=null}player.navStuck=0}}}else{player.autoPath=false;player.tapDestination=null;player.moving=false;}}else move(player,0,0,dt);
 for(const a of actors){a.slow=Math.max(0,a.slow-dt);if(a.id){a.planAt-=dt;const target=chooseTarget(a);if(a.target!==target||a.planAt<=0&&a.path.length===0){a.target=target;a.planAt=2;planPath(a,stations.find(s=>s.id===target))}const p=a.path[0];if(p){const dist=Math.hypot(a.x-p.x,a.z-p.z);if(dist<.15)a.path.shift();else move(a,p.x-a.x,p.z-a.z,dt)}else a.moving=false;}
 const st=nearStation(a);if(st?.id!==a.zone){a.zone=st?.id||null;a.dropped=null;a.actionTime=0;a.paintTime=0;if(a.bought!==a.zone)a.bought=null}if(st)interact(a,st,dt);else a.actionTime=0;
 if(!a.id){for(let i=spills.length-1;i>=0;i--){const sp=spills[i];if(Math.hypot(a.x-sp.x,a.z-sp.z)<.55){if(a.moving)a.slow=.6;else{sp.clean+=dt;if(sp.clean>1.1){spills.splice(i,1);S.cleaned++;earn(unitPrice()*.75,sp.x,sp.z,'Cleaning +'+fmt(unitPrice()*.75));toast('Aisle cleaned! Easier to move')}}}}}else for(const sp of spills)if(Math.hypot(a.x-sp.x,a.z-sp.z)<.5)a.slow=.7;}
 spillClock+=dt;if(spillClock>48&&spills.length<3&&S.sold>6){spillClock=0;for(let attempt=0;attempt<20;attempt++){const x=(4+Math.random()*9)*MAP_SCALE,z=(4.6+Math.random()*7.5)*MAP_SCALE;if(!blocked(x,z)&&!stations.some(st=>Math.hypot(x-st.x,z-st.z-1.55)<1)){spills.push({x,z,clean:0});break}}}
 const truckX=(2+(S.time*.45)%15)*MAP_SCALE;if(Math.abs(player.x-truckX)<.5&&Math.abs(player.z-15.3*MAP_SCALE)<.45)player.slow=.5;
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.age+=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.h+=p.vh*dt;p.vh-=11*dt;if(p.h<0){p.h=0;p.vh*=-.25}if(p.age>=p.life)particles.splice(i,1)}for(let i=cashFloats.length-1;i>=0;i--){cashFloats[i].age+=dt;if(cashFloats[i].age>1.8)cashFloats.splice(i,1)}saveTimer+=dt;if(saveTimer>5){saveTimer=0;save()}}
function project(x,z,h=0){if(terrain){x*=MAP_SCALE;z*=MAP_SCALE}return {x:width/2+(x-z)*tile+camX,y:height*.15+(x+z)*tile*.5-h*tile+camY}}
let desat=false;const grayCache=new Map();function gray(c){let g=grayCache.get(c);if(!g){const n=parseInt(c.slice(1,7),16),l=Math.round(((n>>16)*.3+((n>>8)&255)*.59+(n&255)*.11)*.9+16),h=Math.min(255,l).toString(16).padStart(2,'0');g='#'+h+h+h;grayCache.set(c,g)}return g}
function poly(points,color,stroke){if(desat&&color.length===7)color=gray(color);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
function shade(hex,f){const c=parseInt(hex.slice(1),16);return '#'+[c>>16,(c>>8)&255,c&255].map(n=>Math.min(255,Math.max(0,Math.round(n*f))).toString(16).padStart(2,'0')).join('')}
function box(x,z,w,d,h,color,base=0){const a=project(x,z,base+h),b=project(x+w,z,base+h),c=project(x+w,z+d,base+h),dd=project(x,z+d,base+h),bb=project(x+w,z,base),cc=project(x+w,z+d,base),ddd=project(x,z+d,base);poly([b,bb,cc,c],shade(color,.71));poly([dd,c,cc,ddd],shade(color,.88));poly([a,b,c,dd],shade(color,1.1))}
function tileQuad(x,z,w,d,color,h=0){poly([project(x,z,h),project(x+w,z,h),project(x+w,z+d,h),project(x,z+d,h)],color)}
function textAt(text,x,z,h=0,color='#eaf5ed',size=12,weight=600,background=false){const p=project(x,z,h);ctx.font=`${weight} ${size}px system-ui, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';if(background){const w=ctx.measureText(text).width+13;ctx.fillStyle='#183b40e6';ctx.beginPath();ctx.roundRect(p.x-w/2,p.y-10,w,20,4);ctx.fill()}ctx.fillStyle=color;ctx.fillText(text,p.x,p.y)}
function ring(x,z,r,color,widthLine=2,percent=1){const p=project(x,z,.02);ctx.beginPath();ctx.ellipse(p.x,p.y,r*tile,r*tile*.5,0,0,Math.PI*2*percent);ctx.strokeStyle=color;ctx.lineWidth=widthLine;ctx.stroke()}
function shadow(x,z,w=1){const p=project(x+.18*w,z+.1*w,.015);ctx.fillStyle='#102b3518';for(const k of [1,.72,.45]){ctx.beginPath();ctx.ellipse(p.x,p.y,tile*w*k,tile*w*k*.45,0,0,Math.PI*2);ctx.fill()}}
function castShadow(x,z,w,d,len){poly([project(x-w,z-d,.016),project(x+w,z-d,.016),project(x+w+len,z-d+len*.55,.016),project(x+w+len,z+d+len*.55,.016),project(x-w+len,z+d+len*.55,.016),project(x-w,z+d,.016)],'#102b3524')}
function tree(x,z,scale=1,color='#527d57'){shadow(x,z,.8*scale);box(x-.11*scale,z-.11*scale,.22*scale,.22*scale,.7*scale,'#95704b');box(x-.65*scale,z-.6*scale,1.2*scale,1.1*scale,1.4*scale,color,.7*scale);const p=project(x,z,2.2*scale);poly([{x:p.x,y:p.y-tile*.7*scale},{x:p.x+tile*.8*scale,y:p.y+tile*.6*scale},{x:p.x,y:p.y+tile*scale},{x:p.x-tile*.8*scale,y:p.y+tile*.6*scale}],shade(color,1.08));poly([{x:p.x,y:p.y-tile*.7*scale},{x:p.x+tile*.8*scale,y:p.y+tile*.6*scale},{x:p.x,y:p.y+tile*scale}],shade(color,.82))}
function labelDetail(st){if(!isUnlocked(st))return 'Unlocks in Chapter '+(st.unlock+1);switch(st.id){case 'source':return Math.floor(S.stock)+' pcs';case 'proc':case 'proc2':return 'Raw '+S.raw+' / Parts '+S.parts;case 'pack':return 'Parts '+S.packIn+' / Done '+S.products;case 'gear':return S.gear>=maxUpgrade()?'MAX this chapter':fmt(upgradeCost('gear'))+' · Lv.'+S.gear;case 'workers':return S.workers>=staffLimit()?'Staff cap MAX':fmt(upgradeCost('workers'))+' · '+S.workers+'/'+staffLimit();case 'quality':return S.quality>=maxUpgrade()?'MAX this chapter':fmt(upgradeCost('quality'))+' · Lv.'+S.quality;case 'expand':return S.stage>=24?'All 25 levels done!':fmt(expansionCost())+' · '+S.stageSold+'/'+expansionGoal()+' pcs';case 'cool':return 'Lowers heat';case 'power':return S.power>0?'Boosting '+Math.ceil(S.power)+'s':S.powerCooldown>0?Math.ceil(S.powerCooldown)+'s':'18s boost';case 'supply':return S.refillCooldown>0?Math.ceil(S.refillCooldown)+'s':'Refill stock';case 'scrap':return S.scrap+' pcs';case 'recycle':return 'Sells scrap';case 'paint':return 'Product ×1.6';case 'delivery':return fmt(unitPrice())+' / pc';case 'export':return 'Export pay ×1.35';default:return ''}}
function drawStation(st){const active=stationAvailable(st);ctx.save();desat=!active;ctx.globalAlpha=active?1:.8;const c=active?st.color:'#9baaa4';const x=st.x,z=st.z;castShadow(x,z,1,.7,1.1);box(x-1,z-.7,2,1.4,.18,'#8faaa9');
 if(st.id==='source'||st.id==='scrap'){box(x-.95,z-.62,1.9,1.22,.35,'#a38459',.18);box(x-.88,z-.55,.14,1.05,.75,'#98764b',.45);box(x+.72,z-.55,.14,1.05,.75,'#98764b',.45);box(x-.8,z-.57,1.6,.15,.65,'#bc9562',.5);for(let i=0;i<Math.min(5,Math.ceil((st.id==='source'?S.stock:S.scrap)/6));i++){box(x-.65+(i%2)*.63,z-.37+Math.floor(i/2)*.25,.52,.25,.2,c,.58+Math.floor(i/2)*.17)}}
 else if(st.type==='proc'){box(x-.8,z-.52,1.65,1.05,1.1,c,.18);box(x-.64,z-.43,1.2,.7,.25,'#c2e1dc',1.28);box(x-.53,z-.29,.24,.26,1.15,'#729596',1.4);box(x+.35,z-.29,.24,.26,1.15,'#729596',1.4);box(x-.53,z-.29,1.12,.26,.18,'#d9ded0',2.38);box(x-.22,z-.27,.35,.24,.34,'#374d57',1.65+Math.sin(S.time*6)*.06);box(x-.5,z+.24,.95,.14,.5,'#f6cf6a',.6);const p=project(x+.59,z+.5,1.05);ctx.fillStyle=S.heat>80?'#ff876f':'#bafa66';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(2,tile*.065),0,Math.PI*2);ctx.fill();if(S.raw>0)box(x-.21,z+.52,.42,.27,.17,'#cc9b5c',.23);if(S.heat>60){for(let i=0;i<3;i++){const h=2.7+(S.time*.9+i*.6)%1.5;const p=project(x+.4,z-.2,h);ctx.globalAlpha=active?Math.max(0,.28-(h-2.7)*.15):.1;poly([{x:p.x,y:p.y-6},{x:p.x+8,y:p.y},{x:p.x+3,y:p.y+8},{x:p.x-8,y:p.y+2}],'#d9e9e5')}}}
 else if(st.id==='pack'){box(x-.85,z-.58,1.7,1.1,.85,c,.18);box(x-.85,z-.58,1.7,1.1,.12,'#e6e7ce',1.03);for(let i=0;i<6;i++)box(x-.75+i*.25,z-.4,.1,.8,.06,'#65818a',1.14);box(x+.58,z-.58,.2,1.1,.65,'#dce1bd',1.15);if(S.packIn||S.products){box(x-.32,z-.21,.55,.48,.55,'#d6b475',1.2);box(x-.06,z-.21,.07,.49,.02,'#eaddb7',1.76)}}
 else if(st.id==='delivery'||st.id==='export'){box(x-.97,z-.65,1.95,1.3,.9,c,.18);box(x-.95,z-.63,1.9,1.26,.13,'#f2deae',1.08);box(x-.85,z-.58,.14,1.14,1.15,'#61747d',1.2);box(x+.7,z-.58,.14,1.14,1.15,'#61747d',1.2);box(x-.95,z-.67,1.95,1.36,.16,st.id==='export'?'#8fa5d2':'#789d73',2.35);box(x-.26,z-.15,.52,.35,.22,'#48676c',1.24);if(S.sold>0)box(x+.44,z+.18,.45,.42,.42,'#d3ae71',.18)}
 else if(st.id==='gear'){box(x-.92,z-.58,1.82,1.18,.75,'#858b77',.18);box(x-.96,z-.64,1.92,1.3,.14,c,.93);box(x-.85,z-.55,1.7,.15,1.45,'#738e63',1.04);for(let i=0;i<4;i++)box(x-.67+i*.38,z-.54,.11,.16,.45,i%2?'#d2d6c2':'#92bace',1.6);box(x-.18,z+.08,.32,.34,.16,'#e5e7c2',1.07)}
 else if(st.id==='workers'){box(x-.88,z-.6,1.75,1.2,1.3,c,.18);box(x-.7,z+.57,1.4,.07,.86,'#dae9e4',.51);box(x-.82,z-.65,1.64,1.3,.18,'#4e799c',1.48);box(x-.13,z+.58,.3,.09,.47,'#71968e',.66)}
 else if(st.id==='quality'){box(x-.85,z-.55,1.7,1.1,.85,'#85929b',.18);box(x-.9,z-.58,1.8,1.2,.13,c,1.03);box(x-.5,z-.31,.54,.46,.6,'#dae7f4',1.16);box(x-.38,z-.19,.27,.22,.18,'#ab8ae0',1.76);box(x+.32,z+.14,.22,.2,.4,'#d2b4f0',1.16)}
 else if(st.id==='expand'){box(x-.95,z-.58,.32,1.1,2.4,'#6a846d',.18);box(x+.62,z-.58,.32,1.1,2.4,'#6a846d',.18);box(x-.95,z-.58,1.9,1.1,.28,c,2.58);for(let i=0;i<4;i++)box(x-.57+i*.3,z+.3,.12,.16,.3,i%2?'#d4e8b7':'#6c8f60',.18);box(x-.23,z+.31,.43,.2,.14,'#b9d99a',.51)}
 else if(st.id==='cool'){box(x-.8,z-.6,1.6,1.2,1.2,c,.18);box(x-.8,z-.6,1.6,1.2,.13,'#bee4e6',1.38);for(let i=0;i<4;i++)box(x-.6+i*.33,z+.58,.12,.05,.65,'#508997',.5);box(x+.31,z-.35,.3,.34,.45,'#e5eeea',1.5)}
 else if(st.id==='power'){box(x-.82,z-.55,1.65,1.1,1.1,c,.18);box(x-.58,z+.54,1.1,.07,.65,'#4a6873',.45);box(x-.72,z-.44,.45,.68,.42,'#6c8791',1.28);box(x+.34,z-.34,.2,.45,.68,'#e6d698',1.28)}
 else if(st.id==='supply'){box(x-.88,z-.57,1.74,1.14,.7,'#547863',.18);box(x-.76,z-.44,1.5,.85,.4,c,.88);box(x-.44,z-.26,.6,.45,.4,'#d2b27a',1.27)}
 else if(st.id==='recycle'){box(x-.82,z-.59,1.64,1.18,1.25,c,.18);box(x-.65,z-.38,1.3,.85,.07,'#2d6f62',1.43);box(x-.65,z+.57,1.3,.08,.25,'#aecbbc',.43)}
 else if(st.id==='paint'){box(x-.8,z-.58,1.65,1.16,1,'#b4859d',.18);box(x-.8,z-.58,1.65,1.16,.12,c,1.18);box(x-.65,z-.48,.12,.94,.82,'#d6e1de',1.3);box(x+.55,z-.48,.12,.94,.82,'#d6e1de',1.3);box(x-.65,z-.48,1.32,.94,.15,'#d2b1cc',2.12);box(x-.23,z-.17,.45,.4,.4,'#e0c486',1.31)}
 ctx.globalAlpha=1;desat=false;ctx.restore();}
function gait(a){const phase=a.walkPhase||0,moving=a.moving&&!RM.matches;return {swing:moving?Math.sin(phase)*.34:0,bob:moving?Math.abs(Math.sin(phase))*.1:0,fx:a.facingX??.7,fz:a.facingZ??.7}}
function drawActor(a){shadow(a.x,a.z,.4);const pose=gait(a),size=a.id?1:1.22,color=a.id?'#6bb4df':'#a3d864';const part=(x,z,w,d,h,c,base=0)=>box(a.x+x*size,a.z+z*size,w*size,d*size,h*size,c,base*size);const leg=(side,stride)=>{const x=side<0?-.18:.04,swing=stride;part(x+pose.fx*swing,-.12+pose.fz*swing,.14,.19,.3,'#344c62',.08+Math.max(0,swing)*.55);part(x-.01+pose.fx*swing,-.13+pose.fz*swing,.16,.23,.09,'#3b5568',.02+Math.max(0,swing)*.55)};leg(-1,pose.swing);leg(1,-pose.swing);part(-.21,-.18,.42,.36,.48,color,.36+pose.bob);const armSwing=a.cargo?.025:pose.swing*.9;part(-.33-pose.fx*armSwing,-.15-pose.fz*armSwing,.13,.27,.32,'#e4bd93',.5+pose.bob);part(.2+pose.fx*armSwing,-.15+pose.fz*armSwing,.13,.27,.32,'#e4bd93',.5+pose.bob);part(-.15,-.14,.3,.28,.28,'#eccb9f',.86+pose.bob);part(-.21,-.2,.42,.4,.16,a.id?'#ecb75e':'#fff4b5',1.14+pose.bob);part(-.23,-.2,.46,.49,.04,a.id?'#f6c671':'#fff4b5',1.14+pose.bob);part(-.11,.14,.045,.02,.045,'#3b4b4d',.99+pose.bob);part(.07,.14,.045,.02,.045,'#3b4b4d',.99+pose.bob);if(a.cargo){for(let i=0;i<Math.min(3,Math.ceil(a.count/2));i++){const c=a.cargo==='raw'?'#c39156':a.cargo==='part'?'#bbd8ce':a.cargo==='scrap'?'#92998d':a.premium?'#dab0d9':'#d9b77c';part(-.21,.19,.43,.35,.24,c,.4+i*.26)}if(a.count>2)textAt('×'+a.count,a.x,a.z,1.95,'#f0ffe7',10,700,true)}if(!a.id){ring(a.x,a.z,.5,'#eaffe0',2)}}
function drawTruck(){terrain=true;const x=2+(S.time*.45)%15,z=15.35;shadow(x,z,1);box(x-.8,z-.4,1.6,.85,.28,'#60777f',.12);box(x-.8,z-.4,.55,.85,.64,'#ece2a7',.4);box(x-.7,z-.42,.4,.05,.25,'#719eaf',.68);box(x-.2,z-.39,1,.8,.7,'#e2b67d',.4);for(const dx of [-.5,.5]){box(x+dx,z-.47,.22,.15,.25,'#364a51');box(x+dx,z+.34,.22,.15,.25,'#364a51')}terrain=false}
function onScreen(x,z,terr,m=160){terrain=terr;const p=project(x,z,0);terrain=false;return p.x>-m&&p.x<width+m&&p.y>-m*1.6&&p.y<height+m}
function draw(){const g=ctx.createLinearGradient(0,0,0,height);g.addColorStop(0,'#91bfc0');g.addColorStop(.6,'#bad7bf');g.addColorStop(1,'#7d9e89');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);tile=Math.max(22,Math.min(34,Math.min(width/26,height/13)));const targetX=-(player.x-player.z)*tile,targetY=height*(width<650?.3:.35)-(player.x+player.z)*tile*.5;if(camReset){camX=targetX;camY=targetY;camReset=false}else{camX+=(targetX-camX)*.12;camY+=(targetY-camY)*.12}
 poly([{x:0,y:height*.1},{x:width*.18,y:height*.03},{x:width*.37,y:height*.12},{x:width*.62,y:height*.02},{x:width,y:height*.12},{x:width,y:height*.6},{x:0,y:height*.6}],'#82ab96');poly([{x:0,y:height*.17},{x:width*.15,y:height*.12},{x:width*.4,y:height*.2},{x:width*.74,y:height*.1},{x:width,y:height*.24},{x:width,y:height*.5},{x:0,y:height*.5}],'#92b5a0');
 terrain=true;tileQuad(-7,-7,34,33,'#8dac7d',-.22);tileQuad(-5,16.8,32,3.7,'#748591',-.18);tileQuad(-5,18.3,32,.09,'#cbd1bd',-.16);for(let x=-4;x<27;x+=2.1)tileQuad(x,18.4,1.1,.07,'#ede8c6',-.15);box(-.1,.3,19.3,16.1,.28,'#899c8b',-.28);
 for(let x=0;x<19;x++)for(let z=1;z<16;z++){const q=project(x+.5,z+.5,0);if(q.x<-tile*5||q.x>width+tile*5||q.y<-tile*5||q.y>height+tile*5)continue;const right=x>=13,locked=right&&chapter()===0;const c=locked?(x+z)%2?'#bdc3aa':'#b7bba2':(x+z)%2?'#dbe0c7':'#d3dac2';tileQuad(x,z,1,1,c,.012);if(!locked){const a=project(x,z,.013),b=project(x+1,z,.013),c=project(x+1,z+1,.013);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.strokeStyle='#839b7518';ctx.lineWidth=.6;ctx.stroke()}}
 for(let x=.6;x<18.8;x+=.8)tileQuad(x,15.05,.42,.08,'#e8c968',.021);for(let z=1.6;z<15;z+=1.2){box(-.12,z,.15,.15,.7,'#a7bba1');box(18.91,z,.15,.15,.7,'#a7bba1')}box(-.1,1,.12,13.6,.08,'#c8d5b8',.65);box(19,1,.12,13.6,.08,'#c8d5b8',.65);
 if(chapter()===0){for(let z=1;z<12;z+=.8)tileQuad(13,z,.16,.45,'#ac9c72',.022);textAt('EXPANSION AREA',16,1.2,0,'#827e61',10,700)}
 terrain=false;
 if(chapter()>=3){const left=stations.find(st=>st.id==='proc'),right=stations.find(st=>st.id==='pack'),x=left.x+1.1,z=left.z-.8,w=right.x-left.x-2.2;box(x,z,w,.6,.15,'#5a7578',.65);for(let n=x+.1;n<x+w;n+=.35)box(n,z,.1,.6,.05,'#a5b9b1',.81);for(let i=0;i<3&&S.parts>0;i++)box(x+((S.time*.6+i*.7)%(w-.3)),z+.08,.26,.28,.15,'#c2dbce',.9)}
 const next=player.tapDestination?.station?stations.find(st=>st.id===player.tapDestination.station):player.tapDestination?null:recommendedStation();
 for(const st of stations){if(!isUnlocked(st))continue;const available=stationAvailable(st);ring(st.x,st.z+1.55,.73,available?st.color:'#83948b',available?2:1);if(next?.id===st.id){ring(st.x,st.z+1.55,.96+Math.sin(S.time*4)*.07,player.tapDestination?'#79e9ff':'#f8cb42',4);ring(st.x,st.z+1.55,1.15,player.tapDestination?'#c9f7ff':'#fff4b7',1.5)}if(st.id===player.zone&&player.actionTime>0){ring(st.x,st.z+1.55,.84,'#fbefac',3,Math.min(1,player.actionTime/(st.type==='upgrade'?1.3:.35)))}}
 for(const sp of spills){const p=project(sp.x,sp.z,.02);poly([{x:p.x-10,y:p.y},{x:p.x-4,y:p.y-5},{x:p.x+13,y:p.y-2},{x:p.x+9,y:p.y+6},{x:p.x-5,y:p.y+5}],'#568b9580');if(sp.clean>0)ring(sp.x,sp.z,.5,'#ecffd8',2,sp.clean/1.1)}
 const objects=[];for(const st of stations)if(isUnlocked(st)&&onScreen(st.x,st.z,false))objects.push({depth:st.x+st.z,draw:()=>drawStation(st)});for(const a of actors)if(onScreen(a.x,a.z,false))objects.push({depth:a.x+a.z+.1,draw:()=>drawActor(a)});objects.push({depth:(17+(S.time*.45)%15)*MAP_SCALE,draw:drawTruck});for(const [x,z,s] of [[-2,1,1.2],[-3,5,1.3],[-2,10,1],[-2,14,1.4],[2,-2,1.3],[7,-2,1.1],[12,-2,1.4],[19,-1,1.2],[21,4,1.4],[21,10,1.1],[22,14,1.4]])if(onScreen(x,z,true,260))objects.push({depth:(x+z)*MAP_SCALE,draw:()=>{terrain=true;tree(x,z,s);terrain=false}});
 objects.push({depth:3*MAP_SCALE,draw:()=>{terrain=true;box(3,-3,3.4,2.5,1.7,'#779b8f');box(2.8,-3.2,3.8,2.9,.4,'#55766a',1.7);box(3.5,-.5,.6,.07,.65,'#c7d8cd',.66);terrain=false}});objects.push({depth:9*MAP_SCALE,draw:()=>{terrain=true;box(9,-3,3.5,2.5,2.2,'#94aaa0');box(8.8,-3.2,3.9,2.9,.3,'#627f7a',2.2);box(11,-2.7,.45,.5,1.6,'#bec6ad',2.5);terrain=false}});objects.sort((a,b)=>a.depth-b.depth);for(const o of objects)o.draw();
 for(const st of stations){if(!isUnlocked(st)||!onScreen(st.x,st.z,false))continue;const available=stationAvailable(st),labelY=2.7;textAt(st.name,st.x,st.z,labelY,available?'#f0f6df':'#b5c0b8',width<650?12:11,700,true);textAt(labelDetail(st),st.x,st.z,labelY-.65,available?'#213f42':'#6e8179',10,650,false);if((st.type==='proc'&&S.raw)||(st.id==='pack'&&S.packIn)){const p=project(st.x,st.z,3.35),pct=st.id==='pack'?S.packProgress:st.id==='proc2'?S.secondProgress:S.procProgress;ctx.fillStyle='#345156';ctx.fillRect(p.x-17,p.y,34,3);ctx.fillStyle=st.id==='pack'?'#9ed5fa':'#bafa66';ctx.fillRect(p.x-17,p.y,34*Math.min(1,pct),3)}}
 if(player.tapDestination){if(!player.tapDestination.station){ring(player.tapDestination.x,player.tapDestination.z,.7,'#79e9ff',3);ring(player.tapDestination.x,player.tapDestination.z,.88,'#c9f7ff',1)}drawDestinationPin(player.tapDestination);}
 for(const p of particles){ctx.globalAlpha=Math.max(0,1-p.age/p.life);const q=project(p.x,p.z,p.h);ctx.fillStyle=p.color;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(p.age*4);ctx.fillRect(-p.size*tile,-p.size*tile,p.size*tile*2,p.size*tile*2);ctx.restore()}ctx.globalAlpha=1;for(const f of cashFloats){const p=project(f.x,f.z,3.1+f.age*.9);ctx.globalAlpha=Math.max(0,1-f.age/1.8);ctx.font='bold '+(width<650?20:23)+'px system-ui';ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeStyle='#1e3b3a';ctx.strokeText(f.text,p.x,p.y);ctx.fillStyle='#eaff93';ctx.fillText(f.text,p.x,p.y)}ctx.globalAlpha=1;
 if(drag){ctx.beginPath();ctx.arc(drag.startX,drag.startY,42,0,Math.PI*2);ctx.fillStyle='#12364045';ctx.fill();ctx.strokeStyle='#ffffff65';ctx.lineWidth=2;ctx.stroke();const dx=drag.x-drag.startX,dy=drag.y-drag.startY,l=Math.hypot(dx,dy)||1,m=Math.min(33,l);ctx.beginPath();ctx.arc(drag.startX+dx/l*m,drag.startY+dy/l*m,17,0,Math.PI*2);ctx.fillStyle='#ecffc7a8';ctx.fill();}
 if(S.paused){ctx.fillStyle='#10253288';ctx.fillRect(0,0,width,height);ctx.fillStyle='#f0ffe5';ctx.textAlign='center';ctx.font='700 25px system-ui';ctx.fillText('Paused',width/2,height/2)}
}
function context(){const st=stations.find(s=>s.id===player.zone);let title='Head to the Material Yard',detail='Tap a machine or the floor to walk there. Stop on a ring to work.',icon='🧑‍🔧';if(player.cargo==='raw'){title='Carry materials to the Processor';detail='Stop on the Processor ring to load materials.'}else if(player.cargo==='part'){title='Carry parts to the Packing Bench';detail='Pack them into products, then deliver.'}else if(player.cargo==='product'){title=player.premium?'Deliver the painted product':'Take the product to Delivery';detail=chapter()>=2?'Visit the Paint Booth for ×1.6 price. Delivering earns cash.':'Stop on the Delivery ring to sell.'}else if(player.cargo==='scrap'){title='Take scrap to the Recycler';detail='Sell scrap at the green Recycler.'}else if(S.products>0){title='Collect products at the Packing Bench';detail=S.products+' product(s) waiting.'}else if(S.parts>0&&chapter()<3){title='Collect parts at the Processor';detail='Carry '+S.parts+' part(s) to the Packing Bench.'}
 if(st){icon=st.icon;title=st.name;if(!isUnlocked(st))detail='Unlocks in Chapter '+(st.unlock+1)+'. Grow the business at the Expansion Gate.';else if(st.type==='upgrade'){if(st.id==='expand'){detail=S.stage>=24?'All 25 levels done! Keep upgrading gear and staff to earn more.':S.stageSold<expansionGoal()?`Need ${S.stageSold} / ${expansionGoal()} deliveries. Cost ${fmt(expansionCost())}`:S.money<expansionCost()?`Deliveries met. Cost ${fmt(expansionCost())} / ${fmt(expansionCost()-S.money)} short`:player.bought===st.id?'Expanded. Leave the ring, then return for the next level.':'Stand here 1.3s to expand · '+fmt(expansionCost())}else{const max=st.id==='workers'?staffLimit():maxUpgrade();detail=S[st.id]>=max?'Cap reached for this chapter. More room next chapter.':S.money<upgradeCost(st.id)?`Cost ${fmt(upgradeCost(st.id))} · ${fmt(upgradeCost(st.id)-S.money)} short`:player.bought===st.id?'Purchased. Leave the ring before buying again.':`Stand here 1.3s to buy · ${fmt(upgradeCost(st.id))}`}}
 else if(st.id==='source')detail=S.stock?'Stop to collect materials. Carry up to '+capacity()+' at a time.':'Out of materials. Visit the green Restock to refill.';else if(st.type==='proc')detail=player.cargo==='raw'?'Stop to load materials.':S.parts?'Stop to take finished parts.':'Waiting. Raw '+S.raw+' · Heat '+Math.floor(S.heat)+'%';else if(st.id==='pack')detail=player.cargo==='part'?'Stop to load parts.':S.products?'Stop to take finished products.':'Waiting. Parts '+S.packIn;else if(st.id==='delivery')detail=player.cargo==='product'?'Stop to sell · '+fmt(unitPrice())+' / pc':'Bring finished products here. Raw materials and parts do not sell.';else if(st.id==='cool')detail='Lowers heat of both machines while you stand here.';else if(st.id==='power')detail=S.powerCooldown>0?'Next boost in '+Math.ceil(S.powerCooldown)+'s':'Stop to speed up processing & packing for 18s.';else if(st.id==='supply')detail=S.refillCooldown>0?'Next restock in '+Math.ceil(S.refillCooldown)+'s':'Stop to refill material stock.';else if(st.id==='paint')detail=player.cargo==='product'&&!player.premium?'Stand here 2.2s to paint · delivery value ×1.6':'Bring a finished product to raise its price with paint.';else if(st.id==='scrap')detail=S.scrap+' scrap from processing. Stop here empty-handed to collect.';else if(st.id==='recycle')detail='Stop here with scrap to turn it into cash.';else if(st.id==='export')detail='Exporting products pays ×1.35. Stacks with paint.';}
 for(const sp of spills)if(Math.hypot(player.x-sp.x,player.z-sp.z)<.55){title='Clean the aisle';detail='Stop on a puddle to clean it in 1.1s. Restores speed and pays a reward.';icon='🧹'}$('context-title').textContent=title;$('context-detail').textContent=detail;$('context-icon').textContent=icon;const hold=st?.type==='upgrade'?player.actionTime/1.3:st?.id==='paint'?player.paintTime/2.2:0;$('hold-bar').style.width=Math.min(100,hold*100)+'%';$('cargo').textContent=player.cargo?({raw:'Raw',part:'Parts',product:player.premium?'Painted':'Product',scrap:'Scrap'}[player.cargo]+' '+player.count+' / '+capacity()):'Empty · cap '+capacity();}
function updateUI(){$('money').textContent=fmt(S.money);$('income').textContent='Total earned '+fmt(S.total);$('level').textContent=(chapter()+1)+' − '+(level()+1);$('level-name').textContent=CHAPTERS[chapter()]+' · '+SUBLEVELS[level()];$('world-title').textContent=CHAPTERS[chapter()];$('chapter-sub').textContent=`CHAPTER 0${chapter()+1} / 05 · LEVEL ${level()+1} / 5`;$('delivered').textContent=S.sold.toLocaleString()+' pcs';$('unit-price').textContent='1 pc '+fmt(unitPrice())+(S.chain>1?' · Chain ×'+(1+.05*(S.chain-1)).toFixed(2):'');$('order-title').textContent=S.orderUrgent?'Rush Bulk Order':S.orderIndex%2?'Order from a Local Shop':'Order from Town Shop';$('order-count').textContent=S.orderCount+' / '+orderGoal()+' pcs';$('order-reward').textContent='Bonus '+fmt(orderBonus());$('order-bar').style.width=Math.min(100,S.orderCount/orderGoal()*100)+'%';$('order-time').textContent=S.orderUrgent?Math.ceil(S.orderTimer)+'s left. Failing costs nothing.':'Deliveries count toward the order. No deadline.';$('stock').textContent=Math.floor(S.stock)+' / '+stockCap();$('process-stock').textContent=S.raw+' / '+S.parts;$('pack-stock').textContent=S.packIn+' / '+S.products;$('staff-count').textContent=S.workers+' / '+staffLimit()+' staff';$('gear-level').textContent=capacity()+' pcs / Lv.'+S.gear;$('heat').textContent=Math.floor(S.heat)+'% / Pack '+Math.floor(S.packHeat)+'%';$('event-text').textContent=S.heat>80||S.packHeat>80?'Machines overheating! Go to Cooling.':S.power>0?'Power Boost active! '+Math.ceil(S.power)+'s left.':chapter()>=3?'The conveyor is carrying parts to the Packing Bench.':S.scrap>0?S.scrap+' scrap waiting. Collect and recycle it for side income.':'Gear raises carry capacity. Staff use the same equipment.';$('expand-cost').textContent=S.stage===24?'All levels done':fmt(expansionCost());$('expand-bar').style.width=(S.stage===24?100:Math.min(100,S.money/expansionCost()*100))+'%';$('expand-goal').innerHTML=S.stage===24?'All 25 levels complete!<br>Take on the world\'s orders.':`Delivered ${S.stageSold} / ${expansionGoal()} this level<br>Head to the Expansion Gate at bottom right.`;const growthHtml=CHAPTERS.map((name,c)=>`<div class="chapter ${c===chapter()?'current':c<chapter()?'done':''}"><span class="chapter-num">${c<chapter()?'✓':c+1}</span><span class="chapter-name">${name}</span><div class="nodes">${Array.from({length:5},(_,l)=>`<i class="node ${c*5+l<S.stage?'done':c*5+l===S.stage?'current':''}" title="${c+1}-${l+1} ${SUBLEVELS[l]}"></i>`).join('')}</div></div>`).join('');if(growthHtml!==lastGrowth){lastGrowth=growthHtml;$('growth').innerHTML=growthHtml}$('pause').textContent=S.paused?'Resume':'Pause';context();}
function resize(){const r=canvas.parentElement.getBoundingClientRect();width=Math.max(280,r.width);height=Math.max(360,r.height);const ratio=Math.min(1.5,devicePixelRatio||1);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);camReset=true;}
function release(cancelNavigation=true){drag=null;keys.clear();player.moving=false;if(cancelNavigation===true){player.autoPath=false;player.path=[];player.tapDestination=null}}
canvas.addEventListener('pointerdown',e=>{if(S.paused||e.button!==0)return;e.preventDefault();release(true);canvas.focus({preventScroll:true});const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;drag={id:e.pointerId,startX:x,startY:y,x,y,didDrag:false,tapDest:tapDestinationAt(x,y)};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;const r=canvas.getBoundingClientRect();drag.x=e.clientX-r.left;drag.y=e.clientY-r.top;if(Math.hypot(drag.x-drag.startX,drag.y-drag.startY)>7)drag.didDrag=true;e.preventDefault()});
canvas.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==undefined&&drag.id!==e.pointerId)return;const dest=drag.tapDest,tap=!drag.didDrag;release(false);if(tap)navigatePlayer(dest)});
canvas.addEventListener('pointercancel',()=>release(true));canvas.addEventListener('lostpointercapture',()=>{if(drag)release(true)});window.addEventListener('blur',()=>release(true));window.addEventListener('resize',resize);

const movementKeys=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];window.addEventListener('keydown',e=>{if(movementKeys.includes(e.code)&&!$('help-dialog').open){e.preventDefault();if(!S.paused){player.autoPath=false;player.path=[];player.tapDestination=null;keys.add(e.code)}}});window.addEventListener('keyup',e=>keys.delete(e.code));document.addEventListener('visibilitychange',()=>{release();last=performance.now();save()});window.addEventListener('pagehide',save);
$('panels').onclick=()=>document.body?.classList.toggle('panels-off');if(typeof matchMedia==='function'&&matchMedia('(max-width:780px)').matches)document.body?.classList.add('panels-off');$('pause').onclick=()=>{S.paused=!S.paused;release();updateUI()};$('sound').onclick=()=>{S.sound=!S.sound;$('sound').textContent='Sound '+(S.sound?'ON':'OFF');sound('buy')};$('help').onclick=()=>{helpWasPaused=S.paused;S.paused=true;release();$('help-dialog').showModal();updateUI()};$('close-help').onclick=()=>$('help-dialog').close();$('help-dialog').addEventListener('close',()=>{S.paused=helpWasPaused;release();updateUI()});
function frame(now){const elapsed=Math.min(.1,Math.max(0,(now-last)/1000));last=now;accumulator+=elapsed;while(accumulator>=1/60){update(1/60);accumulator-=1/60}uiTimer+=elapsed;if(uiTimer>.25){uiTimer=0;updateUI()}draw();rafId=requestAnimationFrame(frame)}
load();for(const a of actors)ensureWalkable(a);resize();updateUI();requestAnimationFrame(frame);
const lifecycle=new AbortController();if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_workshop',description:'Read the current factory funds, materials, character cargo and 25-level progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({stage:S.stage+1,chapter:chapter()+1,level:level()+1,money:S.money,stock:S.stock,raw:S.raw,parts:S.parts,products:S.products,workers:S.workers,character:{x:player.x,z:player.z,cargo:player.cargo,count:player.count},expansion:{cost:expansionCost(),quota:expansionGoal(),delivered:S.stageSold}})},{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
