require('node:fs').mkdirSync(require('node:path').join(__dirname, 'artifacts'), {recursive:true});
const path = require('node:path');
const fs=require('fs'),vm=require('vm'),assert=require('assert');const {Canvas}=require('skia-canvas');
function setup(w=980,h=650){const cv=new Canvas(w,h),els=new Map(),events=new Map();function el(id){if(!els.has(id))els.set(id,{id,textContent:'',innerHTML:'',style:{},open:false,classList:{add(){},remove(){},toggle(){}},addEventListener(name,f){events.set(id+':'+name,f)},querySelector(){return el(id+':child')},getBoundingClientRect(){return {left:0,top:0,width:w,height:h}},focus(){},setPointerCapture(){},showModal(){this.open=true},close(){this.open=false},parentElement:{getBoundingClientRect(){return {width:w,height:h}}},getContext:()=>cv.getContext('2d')});return els.get(id)}const can=el('game');Object.defineProperty(can,'width',{set:v=>cv.width=v,get:()=>cv.width});Object.defineProperty(can,'height',{set:v=>cv.height=v,get:()=>cv.height});const storage=new Map();let frame;const context={console,document:{getElementById:el,addEventListener(){},activeElement:{tagName:'CANVAS'}},window:{addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},performance:{now:()=>0},devicePixelRatio:1,matchMedia:()=>({matches:false}),AbortController,setTimeout:()=>1,clearTimeout(){},requestAnimationFrame:f=>{frame=f}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname, "engine.js"),'utf8'),context);const run=s=>vm.runInContext(s,context);return {run,cv,events,els,storage}}
function advance(g,t){g.run(`for(let i=0;i<${Math.ceil(t*60)};i++)update(1/60)`)}
function travel(g,id){assert(g.run(`navigatePlayer({x:stations.find(s=>s.id==='${id}').x,z:stations.find(s=>s.id==='${id}').z+1.55,station:'${id}'})`));let ticks=0;while(g.run('player.autoPath')&&ticks<3600){g.run('update(1/60)');ticks++}assert(ticks<3600,'Path stuck '+id);return ticks/60}

(async()=>{let g=setup();for(let i=0;i<6;i++)g.run('draw()');await g.cv.toFile(path.join(__dirname, 'artifacts', "SHIFT-v2-desktop.png"));g.run('S.money=1000');g.events.get('game:pointerdown')({button:0,pointerId:1,clientX:100,clientY:100,preventDefault(){}});g.events.get('game:pointermove')({pointerId:1,clientX:140,clientY:100,preventDefault(){}});const before=g.run('player.x');advance(g,.5);assert.notEqual(g.run('player.x'),before);g.events.get('game:pointerup')({pointerId:1});const stopped=g.run('player.x');advance(g,.3);assert.equal(g.run('player.x'),stopped);console.log('PASS drag movement and release stop');
 g=setup();travel(g,'source');advance(g,1);assert.equal(g.run('player.cargo'),'raw');assert.equal(g.run('player.count'),2);travel(g,'delivery');advance(g,1);assert.equal(g.run('S.money'),0);travel(g,'proc');advance(g,5);assert.equal(g.run('player.cargo'),'part');assert.equal(g.run('player.count'),2);travel(g,'pack');advance(g,4);assert.equal(g.run('player.cargo'),'product');assert.equal(g.run('player.count'),2);travel(g,'delivery');advance(g,1);assert.equal(g.run('S.sold'),2);assert.equal(g.run('S.money'),28);console.log('PASS physical material -> processing -> packing -> delivery; raw cannot be sold');
 g.run('S.money=1000');travel(g,'gear');advance(g,1.5);assert.equal(g.run('S.gear'),1);advance(g,8);assert.equal(g.run('S.gear'),1);travel(g,'source');travel(g,'gear');advance(g,1.5);assert.equal(g.run('S.gear'),2);console.log('PASS location upgrades, purchase dwell and no repeat spending');
 g.run('S.stageSold=0');travel(g,'expand');advance(g,2);assert.equal(g.run('S.stage'),0);g.run('S.stageSold=expansionGoal()');advance(g,2);assert.equal(g.run('S.stage'),1);console.log('PASS expansion requires money and delivery quota');
 for(let stage=2;stage<25;stage++){g.run(`S.stageSold=expansionGoal();S.money=expansionCost();player.bought=null;`);advance(g,1.5);assert.equal(g.run('S.stage'),stage)}assert.equal(g.run('expandAt()'),false);console.log('PASS all 25 stages and final-stage guard');
 g.run('S.heat=95;S.packHeat=90;player.cargo=null');travel(g,'cool');advance(g,2);assert(g.run('S.heat')<30);g.run("player.cargo='product';player.count=2;player.premium=false");travel(g,'paint');advance(g,2.4);assert.equal(g.run('player.premium'),true);console.log('PASS cooling and premium painting');
 g=setup();g.run("S.money=1000;buyAt('workers');buyAt('workers');player.x=1.2;player.z=15.6");advance(g,300);const sold=g.run('S.sold'),income=g.run('S.total');assert(sold>=10,'workers must deliver goods');assert(sold<220,'bounded processing prevents runaway income');assert(g.run('S.stock')<=g.run('stockCap()'));assert(g.run('S.raw')<=g.run('bufferCap()'));assert(g.run('S.parts')<=g.run('bufferCap()'));assert(g.run('S.products')<=g.run('bufferCap()'));const money=g.run('S.money');g.run('S.paused=true');advance(g,10);assert.equal(g.run('S.money'),money);console.log('PASS staff physical routing, finite stocks and pause', {fiveMinuteUnits:sold,fiveMinuteRevenue:income});
 g=setup(430,540);g.run('S.stage=10;S.money=240;S.gear=4;S.raw=5;S.parts=2;S.packIn=3;S.products=4;');for(let i=0;i<40;i++)g.run('draw()');await g.cv.toFile(path.join(__dirname, 'artifacts', "SHIFT-v2-mobile.png"));console.log('PASS real Canvas 2D rendering at desktop and mobile sizes');
})().catch(e=>{console.error(e);process.exit(1)})
