require('node:fs').mkdirSync(require('node:path').join(__dirname, 'artifacts'), {recursive:true});
const path = require('node:path');
const fs=require('fs'),vm=require('vm'),assert=require('assert');const {Canvas}=require('skia-canvas');
function setup(w=980,h=650){const cv=new Canvas(w,h),els=new Map(),events=new Map();function el(id){if(!els.has(id))els.set(id,{id,textContent:'',innerHTML:'',style:{},open:false,classList:{add(){},remove(){},toggle(){}},addEventListener(name,f){events.set(id+':'+name,f)},querySelector(){return el(id+':child')},getBoundingClientRect(){return {left:0,top:0,width:w,height:h}},focus(){},setPointerCapture(){},showModal(){this.open=true},close(){this.open=false},parentElement:{getBoundingClientRect(){return {width:w,height:h}}},getContext:()=>cv.getContext('2d')});return els.get(id)}const can=el('game');Object.defineProperty(can,'width',{set:v=>cv.width=v,get:()=>cv.width});Object.defineProperty(can,'height',{set:v=>cv.height=v,get:()=>cv.height});const storage=new Map();let frame;const context={console,document:{getElementById:el,addEventListener(){},activeElement:{tagName:'CANVAS'}},window:{addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},performance:{now:()=>0},devicePixelRatio:1,matchMedia:()=>({matches:false}),AbortController,setTimeout:()=>1,clearTimeout(){},requestAnimationFrame:f=>{frame=f}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname, "engine.js"),'utf8'),context);const run=s=>vm.runInContext(s,context);return {run,cv,events,els,storage}}
function advance(g,t){g.run(`for(let i=0;i<${Math.ceil(t*60)};i++)update(1/60)`)}
function travel(g,id){assert(g.run(`navigatePlayer({x:stations.find(s=>s.id==='${id}').x,z:stations.find(s=>s.id==='${id}').z+1.55,station:'${id}'})`));let ticks=0;while(g.run('player.autoPath')&&ticks<3600){g.run('update(1/60)');ticks++}assert(ticks<3600,'Path stuck '+id);return ticks/60}

(async()=>{const g=setup();g.run('draw()');const point=g.run("project(stations.find(s=>s.id==='source').x,stations.find(s=>s.id==='source').z,2.7)");const start=g.run('({x:player.x,z:player.z})');g.events.get('game:pointerdown')({button:0,pointerId:5,clientX:point.x,clientY:point.y,preventDefault(){}});g.events.get('game:pointerup')({pointerId:5});g.events.get('game:lostpointercapture')();assert.equal(g.run('player.autoPath'),true);assert.equal(g.run('player.tapDestination.station'),'source');assert.equal(g.run('player.x'),start.x);for(let i=0;i<1800&&g.run('player.autoPath');i++)g.run('update(1/60)');assert.equal(g.run('player.autoPath'),false);advance(g,1);assert.equal(g.run('player.cargo'),'raw');console.log('PASS actual equipment tap starts walking, does not teleport, survives capture release and performs arrival work');
const floor=g.run('project(8,11)');const dest=g.run(`tapDestinationAt(${floor.x},${floor.y})`);assert.equal(dest.station,null);assert(Math.abs(dest.x-8)<.001&&Math.abs(dest.z-11)<.001);assert(g.run(`navigatePlayer({x:8,z:11,station:null})`));for(let i=0;i<1800&&g.run('player.autoPath');i++){g.run('update(1/60)');assert.equal(g.run('blocked(player.x,player.z)'),false)}assert(g.run('Math.hypot(player.x-8,player.z-11)')<.15);console.log('PASS floor tap projection and navigation avoiding equipment');
g.run("navigatePlayer({x:20,z:18,station:null})");g.events.get('game:pointerdown')({button:0,pointerId:7,clientX:100,clientY:100,preventDefault(){}});g.events.get('game:pointermove')({pointerId:7,clientX:150,clientY:100,preventDefault(){}});assert.equal(g.run('player.autoPath'),false);advance(g,.5);g.events.get('game:pointerup')({pointerId:7});assert.equal(g.run('player.autoPath'),false);const pos=g.run('player.x');advance(g,.5);assert.equal(g.run('player.x'),pos);console.log('PASS drag interrupts tap travel and release stops');
g.run('navigatePlayer({x:15,z:15,station:null});draw()');await g.cv.toFile(path.join(__dirname, 'artifacts', "SHIFT-v4-tap.png"));const html=fs.readFileSync(path.join(__dirname, "index.html"),'utf8'),js=fs.readFileSync(path.join(__dirname, "engine.js"),'utf8');assert(!html.includes('次はここ')&&!js.includes('次はここ'));console.log('PASS destination remains visually marked without next-text');})().catch(e=>{console.error(e);process.exit(1)});
